spring.application.name=CodeExecution Service

# Define Docker images for each language
docker.languages.python=python-executor
docker.languages.java=java-executor

# languages.properties
python.fileExtension=.py
python.runCommand=python

java.fileExtension=.java
java.runCommand=javac && java

server.address=0.0.0.0



